tabPanel("Trees and Bushes",div(id="reset_inputs_tree",
         selectizeInput("trees", "Select type",choices = tree_bush_list,
                        options = list(create = TRUE,placeholder = "Which type was affected?")),
         conditionalPanel(condition ="input.trees!=''",
                          fluidRow(column(6,selectInput("unit_tree","Measurement Unit", choices = list("Ha","M2")))),
                          fluidRow(column(6,numericInput("lost_tree", "Units lost", min = 0, value = 0)),
                                   conditionalPanel(condition="input.lost_tree>0",
                                                    column(6, numericInput("replacement_tree",
                                                                           "Years until Replacement is Productive",
                                                                           min = 0, value = 0)))),
                          fluidRow(column(4,numericInput("reduced_tree","Units with Reduced Yield",min = 0, value = 0)),
                                   conditionalPanel(condition ="input.reduced_tree >0",
                                                    column(4,
                                                           numericInput("recover_tree","Years until yields recover",
                                                                        min = 0, value = 0)),
                                                    column(4, sliderInput("reduction_tree","Share of Reduction",
                                                                          min = 0, step = 5, max = 100, value = 75)))),
                          fluidRow(column(2,actionButton("default_tree","Use Defaults",
                                                         style = "background-color: #337ab7; border-color: #2e6da4;
                                                         color: white")),
                                   column(2,actionButton("create_custom_tree","Create Custom",
                                                         style = "background-color: orange; border-color: orange;
                                                         color: white"))))))
